# Generated by Django 4.1.7 on 2023-08-14 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('description', models.TextField(max_length=150)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.TextField(max_length=5)),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savingsApp.bot_user')),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('savings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savingsApp.savings')),
            ],
        ),
    ]
