# Generated by Django 4.1.7 on 2023-08-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsApp', '0003_alter_operations_savings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='currency',
            field=models.TextField(max_length=10),
        ),
    ]
